# Generated by Django 5.2.1 on 2025-05-19 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('interactive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aula', models.CharField(max_length=100)),
                ('codigo_aula', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EpocaFloracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoca_floracion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('archivo_multimedia', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDeConservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('LC', 'Preocupación menor'), ('NT', 'Casi amenazada'), ('VU', 'Vulnerable'), ('EN', 'En peligro'), ('CR', 'En peligro crítico')], max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GradoDeNivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModoDeReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_reproduccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeligroHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_peligro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_animal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadoNivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFlor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_flor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_institucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_juego', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_multimedia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproduccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suelo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsosAlimenticios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usos_alimenticios', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsosMedicinales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usos_medicinales', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='species',
            name='category',
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciesimage',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciessound',
            name='species',
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='url',
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/'),
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='titulo',
            field=models.CharField(default='Sin titulo', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fauna',
            fields=[
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.especie')),
                ('tiempo_gestacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_crias', models.CharField(blank=True, max_length=50, null=True)),
                ('tamaño', models.CharField(max_length=10)),
                ('peso', models.CharField(blank=True, max_length=10, null=True)),
                ('modo_reproduccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.mododereproduccion')),
                ('tipo_alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipoalimentacion')),
                ('tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.especie')),
                ('altura_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='estado_conservacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.estadodeconservacion'),
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo_url', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.categoria')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.especie')),
                ('grado_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.gradodeniveleducativo')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.niveleducativo')),
                ('tipo_multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipomultimedia')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('instrucciones', models.TextField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.aula')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ficha')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipoactividad')),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.habitat'),
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=200)),
                ('numero_calle', models.CharField(max_length=10)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.distrito')),
                ('tipo_calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipocalle')),
                ('tipo_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipoinstitucion')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.institucion'),
        ),
        migrations.AddField(
            model_name='especie',
            name='locacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.locacion'),
        ),
        migrations.AddField(
            model_name='especie',
            name='peligro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.peligrohumano'),
        ),
        migrations.AddField(
            model_name='especie',
            name='tipo_especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='content.tipoespecie'),
        ),
        migrations.CreateModel(
            name='Floracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('epoca_floracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.epocafloracion')),
                ('tipo_flor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.tipoflor')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=100)),
                ('instrucciones', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel_dificultad', models.IntegerField()),
                ('tipo_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipojuego')),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='tipo_multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipomultimedia'),
        ),
        migrations.AddField(
            model_name='especie',
            name='tipo_reproduccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tiporeproduccion'),
        ),
        migrations.CreateModel(
            name='Usos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('usos_alimenticios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.usosalimenticios')),
                ('usos_medicinales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.usosmedicinales')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado_nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.tipoestadoniveleducativo')),
                ('grado_nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.gradodeniveleducativo')),
                ('nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.niveleducativo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.rol')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecompensaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'juego')},
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='JuegoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('fecha_jugada', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'juego', 'fecha_jugada')},
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ficha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_avistamiento', models.DateField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('comentario', models.CharField(max_length=200)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.especie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AulaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion_aula', models.CharField(max_length=50)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.aula')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.usuario')),
            ],
            options={
                'unique_together': {('aula', 'estudiante')},
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.usuario'),
        ),
        migrations.DeleteModel(
            name='SpeciesCategory',
        ),
        migrations.DeleteModel(
            name='SpeciesImage',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='SpeciesSound',
        ),
        migrations.AddField(
            model_name='flora',
            name='floracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.floracion'),
        ),
        migrations.AddField(
            model_name='flora',
            name='tipo_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tipoplanta'),
        ),
        migrations.AddField(
            model_name='flora',
            name='tipo_suelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tiposuelo'),
        ),
        migrations.AddField(
            model_name='flora',
            name='usos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.usos'),
        ),
    ]
