# Generated by Django 5.2.1 on 2025-05-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_aula_categoria_distrito_epocafloracion_especie_and_more'),
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='species',
            field=models.ManyToManyField(blank=True, to='content.especie'),
        ),
    ]
