# Generated by Django 4.2.7 on 2025-06-21 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Imagen'), ('document', 'Documento'), ('interactive', 'Interactivo')], max_length=20, verbose_name='Tipo de medio')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='multimedia/videos/', verbose_name='Archivo de video')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='multimedia/audio/', verbose_name='Archivo de audio')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='multimedia/images/', verbose_name='Imagen')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='multimedia/documents/', verbose_name='Documento')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='URL externa')),
                ('educational_level', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('universidad', 'Universidad'), ('general', 'General')], default='general', max_length=20, verbose_name='Nivel educativo')),
                ('subject_area', models.CharField(blank=True, max_length=100, verbose_name='Área temática')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='Objetivos de aprendizaje')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (minutos)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de vistas')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Número de descargas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_cards', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_cards', to='common.category', verbose_name='Categoría')),
                ('locations', models.ManyToManyField(blank=True, related_name='multimedia_cards', to='common.location', verbose_name='Ubicaciones relacionadas')),
            ],
            options={
                'verbose_name': 'Ficha multimedia',
                'verbose_name_plural': 'Fichas multimedia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Etiqueta multimedia',
                'verbose_name_plural': 'Etiquetas multimedia',
            },
        ),
        migrations.CreateModel(
            name='MultimediaCardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimedia_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.multimediacard')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.multimediatag')),
            ],
            options={
                'unique_together': {('multimedia_card', 'tag')},
            },
        ),
    ]
