# Generated by Django 5.2.1 on 2025-07-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('multimedia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediacard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_cards', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='multimediacard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_cards', to='common.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='multimediacard',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='multimedia_cards', to='common.location', verbose_name='Ubicaciones relacionadas'),
        ),
        migrations.AddField(
            model_name='multimediacardtag',
            name='multimedia_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.multimediacard'),
        ),
        migrations.AddField(
            model_name='multimediacardtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.multimediatag'),
        ),
        migrations.AlterUniqueTogether(
            name='multimediacardtag',
            unique_together={('multimedia_card', 'tag')},
        ),
    ]
