# Generated by Django 5.2.1 on 2025-07-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('multimedia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediacard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_cards', to='common.category', verbose_name='Categoría'),
        ),
    ]
