# Generated by Django 5.2.1 on 2025-07-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='folder', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Contenido',
                'verbose_name_plural': 'Categorías de Contenido',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=500)),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Dificultad')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='educational_sheets/images/', verbose_name='Imagen destacada')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='educational_sheets/attachments/', verbose_name='Archivos adjuntos')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('in_review', 'En Revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('published', 'Publicada'), ('archived', 'Archivada')], default='draft', max_length=20, verbose_name='Estado')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas de revisión')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizaciones')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Ficha Educativa',
                'verbose_name_plural': 'Fichas Educativas',
                'ordering': ['-created_at'],
                'permissions': [('can_review_sheets', 'Puede revisar fichas'), ('can_publish_sheets', 'Puede publicar fichas'), ('can_moderate_content', 'Puede moderar contenido')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template', models.CharField(help_text='Ruta de la plantilla HTML específica para este lugar', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('map_url', models.URLField(blank=True, help_text='URL de Google Maps para este lugar', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SheetRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creada'), ('submitted', 'Enviada para revisión'), ('reviewed', 'Revisada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('published', 'Publicada'), ('edited', 'Editada'), ('archived', 'Archivada')], max_length=20, verbose_name='Acción')),
                ('notes', models.TextField(blank=True, verbose_name='Notas/Comentarios')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Número de versión')),
                ('changes_summary', models.TextField(blank=True, verbose_name='Resumen de cambios')),
                ('status_before', models.CharField(blank=True, max_length=20, verbose_name='Estado anterior')),
                ('status_after', models.CharField(blank=True, max_length=20, verbose_name='Estado posterior')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Historial de Revisión',
                'verbose_name_plural': 'Historial de Revisiones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('content_type', models.CharField(choices=[('comment', 'Comentario'), ('question', 'Pregunta'), ('answer', 'Respuesta'), ('project', 'Proyecto'), ('drawing', 'Dibujo'), ('story', 'Historia')], max_length=20, verbose_name='Tipo de contenido')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('flagged', 'Marcado')], default='pending', max_length=20, verbose_name='Estado de moderación')),
                ('moderation_notes', models.TextField(blank=True, verbose_name='Notas de moderación')),
                ('moderation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de moderación')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='student_content/', verbose_name='Archivo adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Contenido de Estudiante',
                'verbose_name_plural': 'Contenido de Estudiantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
