# Generated by Django 5.2.1 on 2025-05-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('habitat', models.TextField()),
                ('diet', models.TextField()),
                ('conservation_status', models.CharField(choices=[('LC', 'Preocupación menor'), ('NT', 'Casi amenazada'), ('VU', 'Vulnerable'), ('EN', 'En peligro'), ('CR', 'En peligro crítico')], max_length=2)),
                ('fun_fact', models.TextField(blank=True)),
                ('is_local', models.BooleanField(default=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Especies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de especies',
            },
        ),
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('image', 'Imagen'), ('audio', 'Audio'), ('link', 'Enlace')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ManyToManyField(blank=True, to='content.species')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.speciescategory'),
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='species/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(upload_to='sounds/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='content.species')),
            ],
        ),
    ]
