# Generated by Django 4.2.7 on 2025-07-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template', models.CharField(help_text='Ruta de la plantilla HTML específica para este lugar', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
            ],
        ),
    ]
