# Generated by Django 4.2.7 on 2025-07-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='map_url',
            field=models.URLField(blank=True, help_text='URL de Google Maps para este lugar', null=True),
        ),
    ]
