# Generated by Django 5.2.1 on 2025-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalsheet',
            name='sheet_type',
            field=models.CharField(choices=[('flora', 'Flora'), ('fauna', 'Fauna'), ('ecosystem', 'Lugar/Ecosistema')], default='flora', max_length=20, verbose_name='Tipo de Ficha'),
        ),
    ]
