# Generated by Django 5.2.1 on 2025-06-17 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('capability', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='capability',
            field=models.CharField(default='Pensamiento Crítico', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='grade',
            field=models.CharField(default='Primer Grado', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='steps',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.CharField(max_length=200)),
                ('capability', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamifiedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('capability', models.CharField(max_length=50)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1)),
                ('accumulated_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('objectives', models.JSONField(default=list)),
                ('points', models.IntegerField()),
                ('progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('capability', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_points', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('capability', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(blank=True, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
