# Generated by Django 5.2.1 on 2025-06-19 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_triviaquestion_challenge_capability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='user',
        ),
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='earned_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reward',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='earned_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='capability',
            field=models.CharField(choices=[('Pensamiento Crítico', 'Pensamiento Crítico'), ('Resolución de Problemas', 'Resolución de Problemas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='capability',
            field=models.CharField(choices=[('Pensamiento Crítico', 'Pensamiento Crítico'), ('Resolución de Problemas', 'Resolución de Problemas')], default='Pensamiento Crítico', max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='grade',
            field=models.CharField(choices=[('Primer Grado', 'Primer Grado'), ('Segundo Grado', 'Segundo Grado')], default='Primer Grado', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gamifiedactivity',
            name='capability',
            field=models.CharField(choices=[('Pensamiento Crítico', 'Pensamiento Crítico'), ('Resolución de Problemas', 'Resolución de Problemas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gamifiedactivity',
            name='grade',
            field=models.CharField(choices=[('Primer Grado', 'Primer Grado'), ('Segundo Grado', 'Segundo Grado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='capability',
            field=models.CharField(choices=[('Pensamiento Crítico', 'Pensamiento Crítico'), ('Resolución de Problemas', 'Resolución de Problemas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Especial', 'Especial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='capability',
            field=models.CharField(choices=[('Pensamiento Crítico', 'Pensamiento Crítico'), ('Resolución de Problemas', 'Resolución de Problemas')], default='Pensamiento Crítico', max_length=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(upload_to='rewards/'),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='capability',
            field=models.CharField(choices=[('Pensamiento Crítico', 'Pensamiento Crítico'), ('Resolución de Problemas', 'Resolución de Problemas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='grade',
            field=models.CharField(choices=[('Primer Grado', 'Primer Grado'), ('Segundo Grado', 'Segundo Grado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trivia_images/'),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
