# Generated by Django 5.2.1 on 2025-07-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('IDactividad', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('Instrucciones', models.TextField(verbose_name='Instrucciones')),
                ('IDficha', models.IntegerField(verbose_name='ID de Ficha')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='AulaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DenominacionAula', models.CharField(max_length=50, verbose_name='Denominación del Aula')),
            ],
            options={
                'verbose_name': 'Aula-Estudiante',
                'verbose_name_plural': 'Aulas-Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('IDaula', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAula', models.CharField(max_length=100, verbose_name='Nombre del Aula')),
                ('CodigoAula', models.CharField(max_length=20, unique=True, verbose_name='Código del Aula')),
                ('Descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('GradoEducativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grado Educativo')),
                ('Seccion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sección')),
                ('IDinstitucion', models.IntegerField(default=1, verbose_name='ID de Institución')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGamificacion',
            fields=[
                ('IDconfiguracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_configuracion', models.CharField(max_length=100, verbose_name='Nombre de Configuración')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración Gamificación',
                'verbose_name_plural': 'Configuraciones Gamificación',
            },
        ),
        migrations.CreateModel(
            name='Desafios',
            fields=[
                ('IDdesafio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('puntos', models.IntegerField(default=0, verbose_name='Puntos')),
                ('nivel_minimo', models.IntegerField(default=1, verbose_name='Nivel Mínimo')),
                ('tipo_desafio', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('especial', 'Especial')], max_length=20, verbose_name='Tipo de Desafío')),
                ('condicion', models.CharField(max_length=200, verbose_name='Condición')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Desafío',
                'verbose_name_plural': 'Desafíos',
            },
        ),
        migrations.CreateModel(
            name='DesafiosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('progreso_actual', models.IntegerField(default=0, verbose_name='Progreso Actual')),
            ],
            options={
                'verbose_name': 'Desafío Usuario',
                'verbose_name_plural': 'Desafíos Usuario',
            },
        ),
    ]
