# Generated by Django 5.2.1 on 2025-07-13 22:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasUsuario',
            fields=[
                ('IDusuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('actividades_completadas', models.IntegerField(default=0, verbose_name='Actividades Completadas')),
                ('juegos_jugados', models.IntegerField(default=0, verbose_name='Juegos Jugados')),
                ('insignias_obtenidas', models.IntegerField(default=0, verbose_name='Insignias Obtenidas')),
                ('desafios_completados', models.IntegerField(default=0, verbose_name='Desafíos Completados')),
                ('tiempo_total_juego', models.IntegerField(default=0, verbose_name='Tiempo Total de Juego (minutos)')),
                ('puntuacion_total', models.IntegerField(default=0, verbose_name='Puntuación Total')),
                ('racha_actual', models.IntegerField(default=0, verbose_name='Racha Actual')),
                ('mejor_racha', models.IntegerField(default=0, verbose_name='Mejor Racha')),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
            ],
            options={
                'verbose_name': 'Estadística Usuario',
                'verbose_name_plural': 'Estadísticas Usuario',
            },
        ),
        migrations.CreateModel(
            name='Insignias',
            fields=[
                ('IDinsignia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='insignias/', verbose_name='Imagen')),
                ('condicion', models.CharField(max_length=200, verbose_name='Condición')),
                ('puntos_requeridos', models.IntegerField(default=0, verbose_name='Puntos Requeridos')),
                ('tipo_insignia', models.CharField(choices=[('especies_expert', 'Experto en Especies'), ('quiz_master', 'Maestro de Cuestionarios'), ('speed_demon', 'Demonio de Velocidad'), ('explorer', 'Explorador'), ('conservationist', 'Conservacionista'), ('collector', 'Coleccionista'), ('first_activity', 'Primera Actividad'), ('perfect_score', 'Puntuación Perfecta'), ('streak_3', 'Racha de 3'), ('streak_7', 'Racha de 7'), ('streak_30', 'Racha de 30')], max_length=20, verbose_name='Tipo de Insignia')),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
            },
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('IDusuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('puntos_acumulados', models.IntegerField(default=0, verbose_name='Puntos Acumulados')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('IDpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(verbose_name='Pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('texto_corto', 'Texto Corto')], default='opcion_multiple', max_length=20, verbose_name='Tipo de Pregunta')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('puntos', models.IntegerField(default=10, verbose_name='Puntos')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['IDtest', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('IDtipoActividad', models.AutoField(primary_key=True, serialize=False)),
                ('TipoActividad', models.CharField(max_length=100, verbose_name='Tipo de Actividad')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividades',
            },
        ),
        migrations.CreateModel(
            name='TipoJuego',
            fields=[
                ('IDtipoJuego', models.IntegerField(primary_key=True, serialize=False)),
                ('TipoJuego', models.CharField(max_length=50, verbose_name='Tipo de Juego')),
            ],
            options={
                'verbose_name': 'Tipo de Juego',
                'verbose_name_plural': 'Tipos de Juegos',
            },
        ),
        migrations.AddField(
            model_name='aulaestudiante',
            name='IDestudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='aulas',
            name='IDdocente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='aulaestudiante',
            name='IDaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.aulas', verbose_name='Aula'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='IDaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.aulas', verbose_name='Aula'),
        ),
        migrations.AddField(
            model_name='desafiosusuario',
            name='IDdesafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.desafios', verbose_name='Desafío'),
        ),
        migrations.AddField(
            model_name='desafiosusuario',
            name='IDusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='LogGamificacion',
            fields=[
                ('IDlog', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=50, verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('puntos_ganados', models.IntegerField(default=0, verbose_name='Puntos Ganados')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
                ('IDusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log Gamificación',
                'verbose_name_plural': 'Logs Gamificación',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('trivia_completed', 'Trivia Completada'), ('activity_completed', 'Actividad Completada'), ('quiz_completed', 'Quiz Completado'), ('achievement_unlocked', 'Logro Desbloqueado'), ('level_up', 'Subida de Nivel')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('IDopcion', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500, verbose_name='Texto de la Opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Es Correcta')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('IDpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['IDpregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('IDprogreso', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('Puntuacion', models.IntegerField(default=0, verbose_name='Puntuación')),
                ('Completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('IDactividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.actividades', verbose_name='Actividad')),
                ('IDusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('IDtest', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Test')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('tiempo_limite', models.IntegerField(default=30, verbose_name='Tiempo Límite (minutos)')),
                ('puntos_por_pregunta', models.IntegerField(default=10, verbose_name='Puntos por Pregunta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('IDaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.aulas', verbose_name='Aula')),
                ('IDdocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='IDtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.test', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='IDtipoActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.tipoactividad', verbose_name='Tipo de Actividad'),
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('IDjuego', models.AutoField(primary_key=True, serialize=False)),
                ('NombreJuego', models.CharField(max_length=100, verbose_name='Nombre del Juego')),
                ('Instrucciones', models.CharField(max_length=500, verbose_name='Instrucciones')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('NivelDificultad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nivel de Dificultad')),
                ('IDtipoJuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.tipojuego', verbose_name='Tipo de Juego')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='aulaestudiante',
            unique_together={('IDaula', 'IDestudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='desafiosusuario',
            unique_together={('IDusuario', 'IDdesafio')},
        ),
        migrations.CreateModel(
            name='InsigniasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Obtenida')),
                ('IDinsignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.insignias', verbose_name='Insignia')),
                ('IDusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Insignia Usuario',
                'verbose_name_plural': 'Insignias Usuario',
                'unique_together': {('IDusuario', 'IDinsignia')},
            },
        ),
        migrations.CreateModel(
            name='JuegoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puntaje', models.IntegerField(default=0, verbose_name='Puntaje')),
                ('FechaJugada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Jugada')),
                ('IDjuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.juegos', verbose_name='Juego')),
                ('IDusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Juego Usuario',
                'verbose_name_plural': 'Juegos Usuario',
                'unique_together': {('IDusuario', 'IDjuego', 'FechaJugada')},
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('IDranking', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_totales', models.IntegerField(default=0, verbose_name='Puntos Totales')),
                ('nivel_actual', models.IntegerField(default=1, verbose_name='Nivel Actual')),
                ('posicion', models.IntegerField(verbose_name='Posición')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('IDaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.aulas', verbose_name='Aula')),
                ('IDusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['-puntos_totales', 'nivel_actual'],
                'unique_together': {('IDaula', 'IDusuario')},
            },
        ),
        migrations.CreateModel(
            name='RecompensasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaObtenida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Obtenida')),
                ('IDjuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.juegos', verbose_name='Juego')),
                ('IDusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recompensa Usuario',
                'verbose_name_plural': 'Recompensas Usuario',
                'unique_together': {('IDusuario', 'IDjuego')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('IDresultado', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion_total', models.IntegerField(default=0, verbose_name='Puntuación Total')),
                ('puntuacion_maxima', models.IntegerField(default=0, verbose_name='Puntuación Máxima')),
                ('porcentaje_acierto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de Acierto')),
                ('preguntas_correctas', models.IntegerField(default=0, verbose_name='Preguntas Correctas')),
                ('total_preguntas', models.IntegerField(default=0, verbose_name='Total de Preguntas')),
                ('tiempo_empleado', models.IntegerField(default=0, verbose_name='Tiempo Empleado (segundos)')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('IDestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('IDtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Resultado de Test',
                'verbose_name_plural': 'Resultados de Tests',
                'ordering': ['-fecha_fin'],
                'unique_together': {('IDtest', 'IDestudiante')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('IDrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, null=True, verbose_name='Respuesta de Texto')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Es Correcta')),
                ('puntos_obtenidos', models.IntegerField(default=0, verbose_name='Puntos Obtenidos')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('IDestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('IDopcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.opcion', verbose_name='Opción Seleccionada')),
                ('IDpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.pregunta', verbose_name='Pregunta')),
                ('IDtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Respuesta de Estudiante',
                'verbose_name_plural': 'Respuestas de Estudiantes',
                'unique_together': {('IDtest', 'IDpregunta', 'IDestudiante')},
            },
        ),
    ]
