# Generated by Django 5.2.1 on 2025-07-09 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_messages', to='gamification.aulas', verbose_name='Classroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_classroom_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Classroom Message',
                'verbose_name_plural': 'Classroom Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Private Message',
                'verbose_name_plural': 'Private Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_message_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_notifications', to='gamification.privatemessage', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message Notification',
                'verbose_name_plural': 'Message Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_conversations_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='User 1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_conversations_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='User 2')),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamification_conversation_last_message', to='gamification.privatemessage', verbose_name='Last Message')),
            ],
            options={
                'verbose_name': 'Private Conversation',
                'verbose_name_plural': 'Private Conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
