# Generated by Django 5.2.1 on 2025-07-13 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_classroommessage_privatemessage_messagenotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='IDdocente',
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Classroom Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Classroom Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grade')),
                ('section', models.CharField(blank=True, max_length=10, null=True, verbose_name='Section')),
                ('institution_id', models.IntegerField(default=1, verbose_name='Institution ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
            },
        ),
        migrations.AlterField(
            model_name='actividades',
            name='IDaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.classroom', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='classroommessage',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_messages', to='gamification.classroom', verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='IDaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.classroom', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='test',
            name='IDaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.classroom', verbose_name='Aula'),
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(max_length=50, verbose_name='Classroom Name')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.classroom', verbose_name='Classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Classroom-Student',
                'verbose_name_plural': 'Classroom-Students',
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='AulaEstudiante',
        ),
        migrations.DeleteModel(
            name='Aulas',
        ),
    ]
