# Generated by Django 5.2.1 on 2025-06-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estudiante'), (2, 'Docente'), (3, 'Padre/Madre'), (4, 'Administrador'), (5, 'Experto')], default=1),
        ),
    ]
