# Generated by Django 5.2.1 on 2025-07-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgame',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='classgame',
            name='virtual_class',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='virtualclass',
            name='students',
        ),
        migrations.RemoveField(
            model_name='virtualclass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('class', 'Clase'), ('assignment', 'Tarea'), ('exam', 'Examen'), ('meeting', 'Reunión'), ('workshop', 'Taller'), ('deadline', 'Fecha límite'), ('reminder', 'Recordatorio'), ('conference', 'Conferencia'), ('project', 'Proyecto'), ('holiday', 'Feriado')], default='class', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='ClassFile',
        ),
        migrations.DeleteModel(
            name='ClassGame',
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.DeleteModel(
            name='VirtualClass',
        ),
    ]
