# Generated by Django 5.2.1 on 2025-07-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
