# Generated by Django 5.2.1 on 2025-06-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_remove_reward_user_badge_users_reward_users_and_more'),
        ('users', '0003_class_studentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='progress_badges', to='gamification.badge'),
        ),
    ]
