# Generated by Django 5.2.1 on 2025-05-19 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Planta',
                'verbose_name_plural': 'Tipos de Planta',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre común')),
                ('scientific_name', models.CharField(max_length=200, verbose_name='Nombre científico')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='species_images/', verbose_name='Imagen')),
                ('audio', models.FileField(blank=True, null=True, upload_to='species_audio/', verbose_name='Audio')),
                ('conservation_status', models.CharField(choices=[('NE', 'No Evaluada'), ('DD', 'Datos Insuficientes'), ('LC', 'Preocupación Menor'), ('NT', 'Casi Amenazada'), ('VU', 'Vulnerable'), ('EN', 'En Peligro'), ('CR', 'En Peligro Crítico'), ('EW', 'Extinta en Estado Silvestre'), ('EX', 'Extinta')], default='NE', max_length=2, verbose_name='Estado de conservación')),
                ('human_danger', models.CharField(choices=[('none', 'Ninguno'), ('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('extreme', 'Extremo')], default='none', max_length=10, verbose_name='Peligro para humanos')),
                ('kingdom', models.CharField(blank=True, max_length=100, verbose_name='Reino')),
                ('phylum', models.CharField(blank=True, max_length=100, verbose_name='Filo')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Clase')),
                ('order', models.CharField(blank=True, max_length=100, verbose_name='Orden')),
                ('family', models.CharField(blank=True, max_length=100, verbose_name='Familia')),
                ('genus', models.CharField(blank=True, max_length=100, verbose_name='Género')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Tamaño')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='Peso')),
                ('lifespan', models.CharField(blank=True, max_length=100, verbose_name='Esperanza de vida')),
                ('diet', models.CharField(blank=True, max_length=200, verbose_name='Dieta')),
                ('habitat', models.TextField(blank=True, verbose_name='Hábitat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='base.category', verbose_name='Categoría')),
                ('locations', models.ManyToManyField(blank=True, related_name='species', to='base.location', verbose_name='Ubicaciones')),
                ('plant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='base.planttype', verbose_name='Tipo de planta')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['name'],
            },
        ),
    ]
