# Generated by Django 5.2.1 on 2025-07-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('pdf', models.FileField(upload_to='guides/', verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
            ],
            options={
                'verbose_name': 'Guía pedagógica',
                'verbose_name_plural': 'Guías pedagógicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
