# Generated by Django 5.2.1 on 2025-07-13 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('pedagogical_guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='bi-file-earmark-text', max_length=50, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Categoría de guía',
                'verbose_name_plural': 'Categorías de guías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuideTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Etiqueta de guía',
                'verbose_name_plural': 'Etiquetas de guías',
            },
        ),
        migrations.RemoveField(
            model_name='guide',
            name='pdf',
        ),
        migrations.AddField(
            model_name='guide',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='guides/audio/', verbose_name='Archivo de audio'),
        ),
        migrations.AddField(
            model_name='guide',
            name='content_type',
            field=models.CharField(choices=[('guide', 'Guía Pedagógica'), ('worksheet', 'Ficha Educativa'), ('multimedia', 'Ficha Multimedia'), ('interactive', 'Contenido Interactivo')], default='guide', max_length=20, verbose_name='Tipo de contenido'),
        ),
        migrations.AddField(
            model_name='guide',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de descargas'),
        ),
        migrations.AddField(
            model_name='guide',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='guide',
            name='educational_level',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('universidad', 'Universidad'), ('general', 'General')], default='general', max_length=20, verbose_name='Nivel educativo'),
        ),
        migrations.AddField(
            model_name='guide',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL externa'),
        ),
        migrations.AddField(
            model_name='guide',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='guides/images/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='guide',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='guide',
            name='learning_objectives',
            field=models.TextField(blank=True, verbose_name='Objetivos de aprendizaje'),
        ),
        migrations.AddField(
            model_name='guide',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='guides', to='common.location', verbose_name='Ubicaciones relacionadas'),
        ),
        migrations.AddField(
            model_name='guide',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='guides/pdfs/', verbose_name='Archivo PDF'),
        ),
        migrations.AddField(
            model_name='guide',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Calificación promedio'),
        ),
        migrations.AddField(
            model_name='guide',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de calificaciones'),
        ),
        migrations.AddField(
            model_name='guide',
            name='subject_area',
            field=models.CharField(blank=True, max_length=100, verbose_name='Área temática'),
        ),
        migrations.AddField(
            model_name='guide',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Archivo de video'),
        ),
        migrations.AddField(
            model_name='guide',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de vistas'),
        ),
        migrations.AddField(
            model_name='guide',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='guides/word/', verbose_name='Archivo Word'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='pedagogical_guides.guidecategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='GuideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de calificación')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pedagogical_guides.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de guía',
                'verbose_name_plural': 'Calificaciones de guías',
                'unique_together': {('guide', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GuideTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='pedagogical_guides.guide')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_relations', to='pedagogical_guides.guidetag')),
            ],
            options={
                'verbose_name': 'Relación guía-etiqueta',
                'verbose_name_plural': 'Relaciones guía-etiqueta',
                'unique_together': {('guide', 'tag')},
            },
        ),
    ]
