# Generated by Django 5.2.1 on 2025-07-13 16:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('assignment', 'Tarea'), ('reading', 'Lectura'), ('test', 'Test'), ('game', 'Juego'), ('worksheet', 'Ficha Educativa'), ('multimedia', 'Ficha Multimedia')], max_length=50, verbose_name='Nombre del Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='bi-file-text', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividades',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(verbose_name='Pregunta')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('true_false', 'Verdadero/Falso'), ('short_answer', 'Respuesta Corta'), ('matching', 'Relacionar')], default='multiple_choice', max_length=20, verbose_name='Tipo de Pregunta')),
                ('points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Puntos')),
                ('order', models.IntegerField(default=1, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('points', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Puntuación')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, otros docentes pueden usar esta actividad como plantilla', verbose_name='¿Es pública?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('due_date', models.DateTimeField(verbose_name='Fecha de Entrega')),
                ('time_limit', models.IntegerField(default=0, help_text='0 = sin límite de tiempo', verbose_name='Tiempo Límite (minutos)')),
                ('allow_late_submission', models.BooleanField(default=False, verbose_name='Permitir entrega tardía')),
                ('max_attempts', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Máximo de intentos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/submissions/', verbose_name='Archivo')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Calificación')),
                ('feedback', models.TextField(blank=True, verbose_name='Comentarios')),
                ('is_late', models.BooleanField(default=False, verbose_name='Entrega tardía')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Número de intento')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='educational_games.assignment', verbose_name='Tarea')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Entrega de Tarea',
                'verbose_name_plural': 'Entregas de Tareas',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('points', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Puntuación')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, otros docentes pueden usar esta actividad como plantilla', verbose_name='¿Es pública?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('game_type', models.CharField(choices=[('quiz', 'Cuestionario'), ('matching', 'Relacionar'), ('drag_drop', 'Arrastrar y Soltar'), ('puzzle', 'Rompecabezas'), ('memory', 'Memoria'), ('classification', 'Clasificación'), ('word_search', 'Sopa de Letras'), ('crossword', 'Crucigrama')], max_length=20, verbose_name='Tipo de Juego')),
                ('game_data', models.JSONField(default=dict, help_text='Configuración específica del juego en formato JSON', verbose_name='Datos del Juego')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=20, verbose_name='Nivel de Dificultad')),
                ('estimated_time', models.IntegerField(default=5, verbose_name='Tiempo Estimado (minutos)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('score', models.IntegerField(default=0, verbose_name='Puntuación')),
                ('max_score', models.IntegerField(default=0, verbose_name='Puntuación Máxima')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Tiempo Empleado (segundos)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('game_data', models.JSONField(default=dict, verbose_name='Datos de la Sesión')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='educational_games.game', verbose_name='Juego')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Sesión de Juego',
                'verbose_name_plural': 'Sesiones de Juegos',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=500, verbose_name='Texto de la Opción')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('order', models.IntegerField(default=1, verbose_name='Orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='educational_games.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta',
                'verbose_name_plural': 'Opciones de Preguntas',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('points', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Puntuación')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, otros docentes pueden usar esta actividad como plantilla', verbose_name='¿Es pública?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('content', models.TextField(verbose_name='Contenido de la Lectura')),
                ('estimated_time', models.IntegerField(default=10, verbose_name='Tiempo Estimado (minutos)')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=20, verbose_name='Nivel de Dificultad')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_readings', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('points', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Puntuación')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, otros docentes pueden usar esta actividad como plantilla', verbose_name='¿Es pública?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('time_limit', models.IntegerField(default=30, verbose_name='Tiempo Límite (minutos)')),
                ('passing_score', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntuación Mínima (%)')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Mezclar preguntas')),
                ('show_results_immediately', models.BooleanField(default=True, verbose_name='Mostrar resultados inmediatamente')),
                ('allow_multiple_attempts', models.BooleanField(default=False, verbose_name='Permitir múltiples intentos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='educational_games.test', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('score', models.IntegerField(default=0, verbose_name='Puntuación')),
                ('max_score', models.IntegerField(default=0, verbose_name='Puntuación Máxima')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Tiempo Empleado (segundos)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='educational_games.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Intento de Test',
                'verbose_name_plural': 'Intentos de Tests',
                'ordering': ['-started_at'],
                'unique_together': {('test', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competency', models.CharField(choices=[('comunicacion', 'Comunicación'), ('pensamiento_critico', 'Pensamiento Crítico'), ('resolucion_problemas', 'Resolución de Problemas'), ('creatividad', 'Creatividad'), ('colaboracion', 'Colaboración'), ('autonomia', 'Autonomía'), ('responsabilidad', 'Responsabilidad'), ('empatia', 'Empatía')], max_length=50, verbose_name='Competencia')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Puntuación')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_evaluations', to='educational_games.assignmentsubmission', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Evaluación por Competencia',
                'verbose_name_plural': 'Evaluaciones por Competencias',
                'unique_together': {('submission', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Tiempo Dedicado (segundos)')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='educational_games.reading', verbose_name='Lectura')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Progreso de Lectura',
                'verbose_name_plural': 'Progresos de Lecturas',
                'unique_together': {('reading', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('assignment', 'Tarea'), ('reading', 'Lectura'), ('test', 'Test'), ('game', 'Juego')], max_length=20, verbose_name='Tipo de Actividad')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_games.assignment', verbose_name='Tarea')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_activities', to='gamification.classroom', verbose_name='Aula')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_games.game', verbose_name='Juego')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_games.reading', verbose_name='Lectura')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_games.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Actividad de Aula',
                'verbose_name_plural': 'Actividades de Aula',
                'unique_together': {('classroom', 'activity_type', 'assignment', 'reading', 'test', 'game')},
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, verbose_name='Respuesta de Texto')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Puntos Obtenidos')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_games.question', verbose_name='Pregunta')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_games.questionoption', verbose_name='Opción Seleccionada')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='educational_games.testattempt', verbose_name='Intento')),
            ],
            options={
                'verbose_name': 'Respuesta de Test',
                'verbose_name_plural': 'Respuestas de Tests',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
